### ISSUE TITLE
Fix Read More/Read Less in Community Feedback section

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeoss#20]
The Read More/Read Less link in the Community Feedback section in the Dataset detail page works on first click, but afterwards does not collapse the content of the comment

**Comment by kmbn** [comment]
This is broken on CKAN all the way up to 2.7.2, but it does work with the current bleeding edge on master (unfortunately, the bleeding edge breaks other things—but the fix is in there somwhere).

**Comment by kmbn** [comment]
CKAN 2.7.2 still includes bootstrap.js version 2.3.2. collapse.js doesn't work properly in bootstrap.js 2.3.2 and that's why the Read More/Read Less link doesn't work.

The latest version of CKAN on master includes bootstrap version 3.3.7, which has a working version of collapse.js.

Checking out CKAN 2.7.2 and then swapping bootstrap.js v2.3.2 for v3.3.7 resolves the issue.

**Comment by kmbn** [comment]
@JGulic Should we just replace bootstrap.js v2.3.2 with v3.3.7 in our branch of CKAN for the portal? Or is there a better way to patch/override the version of bootstrap.js that CKAN uses?

**Comment by kmbn** [comment]
#38 Just bypasses bootstrap.js entirely, so we don't need to worry about the version.

**Comment by kmbn** [comment]
Fixed in #38
